version: '3.3'

services:
  service_1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  service_2:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    ports:
      - 8001:8001

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - backend