version: '3.3'

services:
  model_1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    expose:
      - 8000

  model_2:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    expose:
      - 8001

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - model_1
      - model_2