version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: test:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  model_1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      KAFKA_SERVER: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: test

  model_2:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    expose:
      - 8001

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - model_1
      - model_2